version: "3.8"
services:
  backend:
    build: ./backend
    image: 'ticket-backend-task'
    container_name: ticket-backend-task-app
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    container_name: ticket-frontend-task-app
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


# Name Volume
volumes:
  logs: